apiVersion: apps.init0.cn/v1
kind: Application
metadata:
  name: application-sample
  labels:
    app: "nginx"
spec:
  deployment:
#    replicas: 11
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: "nginx"
      spec:
        containers:
          - name: nginx
            image: nginx:1.19
            ports:
              - containerPort: 80
                protocol: TCP
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30080