apiVersion: apps.init0.cn/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: myoperator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: myoperator
  name: application-sample
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80
              protocol: TCP
